---
- name: Install microk8s
  hosts: all
  become: true

  tasks:
    - name: install microk8s
      community.general.snap:
        classic: true
        name: microk8s

    - name: add userpermissions
      ansible.builtin.shell: "usermod -aG microk8s vagrant"
