---
# Kestra ansible-playbook Template
# ---
#
# Run an ansible playbook which has been uploaded to the server.
#
id: ansible_job  # <- Replace with your task id...
namespace: your-namespace  # <- Replace with your namespace...

tasks:
  - id: ansible  # <- Replace with your task id...
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: ansible_task  # <- Replace with your task id...
        namespaceFiles:
          enabled: true
          # --> upload your files to the kestra data directory for the namespace in
          #     <docker volume for kestra-data>/<namespace>/_files/
          include:
            - inventory.ini  # <- Replace with your inventory file...
            - myplaybook.yaml  # <- Replace with your playbook file...
          # <--
        type: io.kestra.plugin.ansible.cli.AnsibleCLI
        docker:
          image: docker.io/cytopia/ansible:latest-tools
        env:
          "ANSIBLE_HOST_KEY_CHECKING": "false"
          # --> (optional) when using a different remote user
          # "ANSIBLE_REMOTE_USER": "your-remote-user"
          # <--
        commands:
          - apk add sshpass  # <- (Optional) Only required if use ssh passwords.
          - ansible-playbook -i inventory.ini myplaybook.yaml  # <- Replace with your inventory and playbook files...
