---
services:
  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/nginx
      - ./data:/usr/share/nginx/html
    restart: unless-stopped
