---
services:
  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/usr/share/nginx/html:ro
    restart: unless-stopped
