---
version: "3.8"

services:
  postgres:
    # (Recommended) replace "latest" with specific version
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # (Optional) when creating a new database
      # - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    # (Optional) when using custom network
    # networks:
    #   - yournetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

# (Optional) when using custom network
# networks:
#   yournetwork:
#     external: true

volumes:
  postgres_data:
