---
services:
  promtail:
    image: grafana/promtail:3.3.3
    command: "-config.file=/mnt/config/config.yaml"
    volumes:
      - ./config/config.yaml:/mnt/config/config.yaml:ro
      - /var/log:/var/log:ro
    restart: unless-stopped
