---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage::v0.8.9
    container_name: homepage
    environment:
      - LOG_LEVEL=info
    # (Optional) Run as a specific user
    #   PUID: $PUID
    #   PGID: $PGID
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config
      # (Optional) For local Docker integration
      # - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
