apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: your-namespace
  labels:
    app: example-app
spec:
  replicas: 3  # how many pods?
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
