apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: your-namespace
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
